config:
  MD013: false
  MD033:
    allowed_elements:
      - details
      - summary
      - br
  MD041: false
  MD060: false

ignores:
  - "**/node_modules"
  - "**/templates"
  - "**/.claude/plans"
