import type { Preset } from "../types.js";
import { readTemplateFiles } from "../utils.js";

/**
 * Library preset — scaffolds an `@ozzylabs/*`-style npm package.
 *
 * Layered on top of `typescript` (auto-resolved via `requires`) and `base`. Adds:
 * - `package.json` overrides for npm publish (scope, files, publishConfig, engines, packageManager)
 * - release-please configuration files
 * - a release workflow (`.github/workflows/release.yaml`)
 * - LICENSE (MIT) and a library-style src/index.ts entry point
 *
 * The preset is opt-in via `WizardAnswers.projectType === "library"`.
 */
export const libraryPreset: Preset = {
  name: "library",
  requires: ["typescript"],
  files: readTemplateFiles("library"),
  merge: {
    "package.json": {
      // Library-specific publishing fields. The project name itself is set by the generator
      // (from `projectName` answer) — leave it untouched here.
      type: "module",
      main: "./dist/index.mjs",
      types: "./dist/index.d.mts",
      files: ["dist"],
      publishConfig: {
        access: "public",
        provenance: true,
      },
      engines: {
        node: ">=22",
      },
      packageManager: "pnpm@10.32.1",
      scripts: {
        prepublishOnly: "pnpm run build",
      },
    },
    ".gitignore": "# Library build output\ndist/\n",
  },
  markdown: {
    "agent-instructions": [
      {
        placeholder: "<!-- SECTION:TECH_STACK -->",
        content: "- **Library**: published as an npm package (`type: module`, ESM-only)",
      },
      {
        placeholder: "<!-- SECTION:PROJECT_STRUCTURE -->",
        content:
          "src/index.ts          -> Library entry point (re-export public API)\ndist/                 -> Build output (gitignored, generated by tsdown)",
      },
      {
        placeholder: "<!-- SECTION:CODING_CONVENTIONS -->",
        content:
          "- Public API surface lives in `src/index.ts`; everything else is internal\n- Bump versions and CHANGELOG via release-please (PR-driven, do not edit `package.json` `version` manually)",
      },
    ],
    "README.md": [
      {
        placeholder: "<!-- SECTION:ROOT_FILES -->",
        content: "├── release-please-config.json\n├── .release-please-manifest.json\n├── LICENSE",
      },
      {
        placeholder: "<!-- SECTION:DIR_STRUCTURE -->",
        content: "├── src/                 # ライブラリのソース（公開 API は `index.ts`）",
      },
    ],
  },
};
